name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - run: echo "We are testing the action"
      - run: echo "Pull Request Id - ${{github.event.pull_request.id}}"
      - run: echo "Pull Request Number - ${{github.event.pull_request.number}}"
      - run: echo "Repo Name - ${{github.event.repository.name}}"
      - run: echo "Repo Name - ${{github.event.repository}}"
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TENOR_TOKEN: ${{secrets.TENOR_TOKEN}} 